BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[cagysData] ALTER COLUMN [rejectionNote] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[cagysData] ALTER COLUMN [notes2] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[cagysData] ALTER COLUMN [notes1] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[cagysData] ALTER COLUMN [rejectionNote2] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[cagysData] ALTER COLUMN [managerNotes] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
